import MoleculesNavbar from "@/components/molecules/m_navbar";
import type { Metadata } from "next";
import "./../globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function FamilyLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const menuItem = [
        { title: "Dashboard", target: "/family" },
        { title: "Task", target: "/family/task" },
        { title: "Calendar", target: "/family/calendar" },
        { title: "Money Flow", target: "/family/money_flow" },
        { title: "Member", target: "/family/member" },
        { title: "Meal", target: "/family/meal" },
        { title: "Inventory", target: "/family/inventory" },
        { title: "Vehicle", target: "/family/vehicle" },
    ]

    return (
        <div className="min-h-screen pt-0 px-5">
            <MoleculesNavbar menuItem={menuItem} isLanding={false} isSignedIn={false}/>
            <div className="mt-5">
                {children}
            </div>
        </div>
    );
}
