import MoleculeFooter from "@/components/molecules/m_footer";
import MoleculesNavbar from "@/components/molecules/m_navbar";
import type { Metadata } from "next";
import "./../globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function FamilyLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    const menuItem = [
        { title: "Dashboard", target: "/family" },
        { title: "Task", target: "/family/task" },
        { title: "Calendar", target: "/family/calendar" },
        { title: "Budget & Saving", target: "/family/budget" },
        { title: "Member", target: "/family/member" },
        { title: "Inventory", target: "/family/inventory" },
        { title: "Vehicle", target: "/family/vehicle" },
        { title: "My Profile", target: "/profile" },
    ]

    return (
        <div className="min-h-screen pt-5 px-5">
            <MoleculesNavbar menuItem={menuItem} isLanding={false}/>
            {children}
        </div>
    );
}
